### ISSUE TITLE
Bug: 모듈 간 의존성 추가 오류

### ISSUE THREAD

**Issue by ksc1008** [kakao-tech-campus-2nd-step3/Team23_Android#34]
### ⚠️ 문제점
모듈 간 의존성을 추가해도 해당 모듈을 임포트할 수 없는 버그가 있습니다.

의존관계를 가지는 두 모듈의 이름이 같은 경우 (ex: `:domain:expense`, `:data:expense`) 해당 오류가 발생하는 것 같습니다.

모듈의 이름을 수정해주면 해당 오류는 해결됩니다.

### 🔍 해결책
이름이 겹치는 모듈의 이름을 수정하여 해결하고자 합니다. 
현재 프로젝트 구조상 data 모듈의 이름만 바꾸어도 해당 문제는 모두 해결될 것 같습니다. 

다만 현재 초기 설정된 모듈 명을 일일이 직접 바꾸지는 않고, gradle 스크립트를 이용해서 수정하려고 합니다.

프로젝트의 `settings.gradle.kts`에 다음 코드를 추가하면 모든 데이터 모듈 명이 `:data:data-moduleName` 형식으로 수정됩니다.
```
project(":data").children.forEach { module -> module.name = "data-${module.name}"}
```
 ---

인터넷에 검색해보았는데 같은 환경이라도 모두가 겪는 문제는 아닌 것 같습니다. 다른 분들도 같은 오류가 발생하는지 궁금하네요.

또 다른 해결책이 있으시다면 의견 남겨주세요!

**Comment by cleonno3o** [comment]
저도 아무리 해도 안되길래 계속 알아보고있었는데 그런 문제였군요!
제시해주신 코드를 추가하니까 정상적으로 import 됩니다!
덕분에 해결했습니다!!👍
